name: Testy Jednostkowe

on: [push, pull_request]

jobs:
  testy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Ustaw Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Zainstaluj zależności
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Uruchom testy
      run: python -m pytest discover -v
